### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by vatterspun** [christau/xp-AntiSpy#2]
I've been trying to determine the license attached to this program.  Softpedia is listing it as ad-supported http://www.softpedia.com/get/Internet/Popup-Ad-Spyware-Blockers/XPAntispy.shtml but what about the code?

**Comment by christau** [comment]
The App itself is GPL, no matter what Softpedia says.
But there was a time (pre 2009) where this Software was closed source and had a static eBay Ad in the UI.

**Comment by vatterspun** [comment]
Thanks for the clarification and for using the GPL with this program.
